#!/bin/bash

# Instructions of pre-defined commands

function print_ALIAS_HOWTO_ {
    cat << EOF
    -------------------------------------------
    Imperial HPC LAMMPS job submitter HOWTO
    -------------------------------------------
    Use 'source ~/.bashrc' to activate pre-defined
    commands

    Pre-defined commands
        Plmp     : Run parallel molecular dynamics by LAMMPS
        Slmp     : Run serial molecular dynamics by LAMMPS
        Xlmp     : Run user defined commands (Advanced)
        SETlmp   : Quick reference of settings file
        HELPlmp  : Print help file

    Example code:
        Plmp -in f2_nvt.in -wt 02:00 -nd 1

    Note:
        Considering the nature of popular MD codes,
        pre-set commands and MPI+executable labels
        are only compitable with the default options.
        Please check the values in EXE_TABLE to
        ensure a successful job submission

        Different the nomenclature adopted in
        popular LAMMPS tutorials, for the input file,
        the file extension must be placed after the
        file name, i.e. jobname.in

        PS. This configuration is also rarely tested.

EOF
}

# Instructions of user-defined commands

function print_GENSUB_HOWTO_ {
    SOURCE=${CTRLDIR}/gen_sub
    source ${SOURCE} -help
}

print_ALIAS_HOWTO_

if [[ $1 == 'gensub' ]]; then
    CONFIGDIR=`realpath $(dirname $0)`
    CTRLDIR=`realpath ${CONFIGDIR}/../`
    print_GENSUB_HOWTO_
fi
