#!/bin/bash  --login
#PBS -N f1_nvt
#PBS -l select=1:ncpus=24:mem=50GB:mpiprocs=24:ompthreads=1:avx2=true
#PBS -l walltime=0:30:00

echo "PBS Job Report"
echo "--------------------------------------------"
echo "  Start Date : $(date)"
echo "  PBS Job ID : ${PBS_JOBID}"
echo "  Status"
qstat -f ${PBS_JOBID}
echo "--------------------------------------------"
echo ""

# number of cores per node used
export NCORES=24
# number of processes
export NPROCESSES=24

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f ${PBS_O_WORKDIR})

# Set the number of threads
export OMP_NUM_THREADS=1

# to sync nodes
cd ${PBS_O_WORKDIR}

# start calculation: command added below by gen_sub
timeout 27m /rds/general/user/hz1420/home/GitHub/crystal_shape_control/Imperial-HPC-Job-Submission/run_exec -set /rds/general/user/hz1420/home/etc/runLAMMPS/settings -in f1_nvt.in -ref  -- 'mpiexec lmp_omp -in f1_nvt.in'
/rds/general/user/hz1420/home/GitHub/crystal_shape_control/Imperial-HPC-Job-Submission/post_proc -in f1_nvt.in -set /rds/general/user/hz1420/home/etc/runLAMMPS/settings


if [[ -f ./f1_nvt.run ]];then
chmod 755 ./f1_nvt.run
./f1_nvt.run
fi
