#!/bin/bash

# Instructions of pre-defined commands
#---- BEGIN_USER ----# Instructions
function print_ALIAS_HOWTO_ {
    cat << EOF
    -------------------------------------------
    Imperial HPC CRYSTAL17 job submitter HOWTO
    -------------------------------------------
    Use 'source ~/.bashrc' to activate pre-defined
    commands

    Pre-defined commands
        Pcrys17    : Run parallel crystal calculations
        MPPcrys17  : Run massive parallel crystal calculations
        Pprop17    : Run parallel properties calculations
        Scrys17    : Run serial crystal calculations
        Sprop17    : Run serial properties calculations
        Xcrys17    : Run user defined commands (Advanced)
        SETcrys17  : Quick reference of settings file
        HELPcrys17 : Print help file

    Example code:
        Pcrys17 -in mgo.d12 -wt 02:00 -nd 2
        Xcrys17 -name mag-band -nd 1 -x pcrystal -in mgo.d12 -wt 01:00 -ref no -x pproperties -in band.d3 -wt 00:30 -ref mgo

EOF
}
#---- END_USER ----#

# Instructions of user-defined commands

function print_GENSUB_HOWTO_ {
    SOURCE=${CTRLDIR}/gen_sub
    source ${SOURCE} -help
}

CONFIGDIR=`realpath $(dirname $0)`
CTRLDIR=`realpath ${CONFIGDIR}/../`

