#!/bin/bash

# Instructions of pre-defined commands

function print_ALIAS_HOWTO_ {
    cat << EOF
    -------------------------------------------
    NHPC101 CRYSTAL23 job submission script HOWTO
    -------------------------------------------
    Use 'source ~/.bashrc' to activate pre-defined
    commands

    Pre-defined commands
        Pcrys23    : Run parallel + OpenMP crystal calculations
        MPPcrys23  : Run massive parallel + OpenMP crystal calculations
        Pprop23    : Run parallel + OpenMP properties calculations
        Scrys23    : Run serial + OpenMP crystal calculations
        Sprop23    : Run serial + OpenMP properties calculations
        Xcrys23    : Run user defined commands (Advanced)
        SETcrys23  : Quick reference of settings file
        HELPcrys23 : Print help file

    Example code:
        Pcrys23 -in mgo.d12 -np 2
        Xcrys23 -name mag-band -np 2 -nt 2 -x pcrys -in mgo.d12 -ref no -x pprop -in band.d3 -ref mgo

EOF
}

# Instructions of user-defined commands

function print_GENSUB_HOWTO_ {
    SOURCE="${CTRLDIR}/run_job"
    bash ${SOURCE} -help
}

print_ALIAS_HOWTO_

if [[ $1 == 'gensub' ]]; then
    CONFIGDIR=`realpath $(dirname $0)`
    CTRLDIR=`realpath ${CONFIGDIR}/../`
    print_GENSUB_HOWTO_
fi
