#!/bin/bash  --login
#PBS -N em-1AKI-em-2BEG
#PBS -l select=1:ncpus=24:mem=50GB:mpiprocs=24:ompthreads=1:avx2=true
#PBS -l walltime=00:20:00

echo "<qsub_standard_output>"
date
echo "<qstat -f ${PBS_JOBID}>"
qstat -f ${PBS_JOBID}
echo "</qstat -f ${PBS_JOBID}>"

# number of cores per node used
export NCORES=24
# number of processes
export NPROCESSES=24

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f ${PBS_O_WORKDIR})

# Set the number of threads
export OMP_NUM_THREADS=1
# env (Uncomment this line to get all environmental variables)
echo "</qsub_standard_output>"

# to sync nodes
cd ${PBS_O_WORKDIR}

# start calculation: command added below by gen_sub
timeout 7m /rds/general/user/hz1420/home/etc/runGROMACS/run_exec -in em-1AKI.tpr  -- 
/rds/general/user/hz1420/home/etc/runGROMACS/post_proc -in em-1AKI.tpr 


timeout 7m /rds/general/user/hz1420/home/etc/runGROMACS/run_exec -in em-2BEG.tpr  -- 
/rds/general/user/hz1420/home/etc/runGROMACS/post_proc -in em-2BEG.tpr 


###
if [[ -f ./em-1AKI-em-2BEG.run ]];then
chmod 755 ./em-1AKI-em-2BEG.run
./em-1AKI-em-2BEG.run
fi
